server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: pkc-lgk0v.us-west1.gcp.confluent.cloud:9092
    properties:
      security.protocol: ${SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL}
      sasl.mechanism: ${SPRING_KAFKA_PROPERTIES_SASL_MECHANISM}
      sasl.jaas.config: ${SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer