services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ft-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest  # Adding version tag
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ft-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - ft-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - kafka
    networks:
      - ft-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/users  # Changed from localhost to service name
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      USER_TOPIC: users

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - mongo
      - kafka
    networks:
      - ft-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/transactions  # Changed from localhost to service name
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TRANSACTION_TOPIC: transactions

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    networks:
      - ft-network
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Change this line: map host port 3000 to container port 80
    depends_on:
      - user-service
      - transaction-service
    networks:
      - ft-network
    environment:
      REACT_APP_USER_SERVICE_URL: http://user-service:8081/api/users
      REACT_APP_TRANSACTION_SERVICE_URL: http://transaction-service:8085/api/transactions

networks:
  ft-network:
    driver: bridge

volumes:
  mongo-data: